#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: James Brink - DevOps Engineer
url: 'https://jamesbrink.github.io/'
baseurl: '' #change it according to your repository name
description: James Brink - DevOps Egnineer
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-83979019-1



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

plugins:
  - jekyll-paginate

exclude:
  - deprecated
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - Gemfile
  - Gemfile.lock


blog-header-img: img/home-bg.jpg

markdown: kramdown
permalink: pretty
highlighter: rouge
paginate: 20
paginate_path: "blog/page:num"
# exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
