[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.0"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
