# Using the default nixfmt command (will be RFC-style in the future)
[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "**/*.html",
  "**/*.scss",
  "**/*.json",
  "**/*.md",
  "**/*.yml",
  "**/*.yaml",
  "**/*.js",
]
excludes = [
  # Jekyll build directories
  "_site/**",
  ".jekyll-cache/**",
  "vendor/**",
  
  # Jekyll special directories with templates
  "_layouts/**",
  "_includes/**",
  "_data/**",
  "_posts/**",  # Jekyll blog posts with front matter
  "_config.yml", # Jekyll configuration
  "blog/**",    # Blog directory
  
  # Binary and asset files
  "**/*.jpg",
  "**/*.jpeg",
  "**/*.png",
  "**/*.gif",
  "**/*.svg",
  "**/*.ico",
  "**/*.eot",
  "**/*.ttf",
  "**/*.woff",
  "**/*.woff2",
  "**/*.otf",
  "**/*.pdf",
  "**/*.docx",
  
  # Config and metadata files
  ".gitignore",
  ".envrc",
  "LICENSE*",
  "CNAME",
  "flake.lock",
  "Gemfile.lock",
  "Gemfile",       # Ruby dependencies
  "README.md",     # Preserve original formatting
  "CLAUDE.md",     # Development documentation
  
  # Third-party and library code
  "assets/plugins/**",
  "**/font-awesome/**",
  "css/**",
  "js/**",         # Exclude all JavaScript in js/ folder
  
  # Minified and compiled files
  "**/min/**",
  "**/min.*",
  "**/*.min.js",
  "**/*.min.css",
  "**/*.css.map",
]

[formatter.yamlfmt]
command = "yamlfmt"
options = []
includes = ["**/*.{yml,yaml}"]
excludes = [
  # Jekyll build directories
  "vendor/**", 
  "_site/**", 
  ".jekyll-cache/**", 
  
  # Jekyll configuration files
  "_config.yml",
  "_data/**/*.yml",
  
  # Third-party files
  "assets/plugins/**/*.yml",
  "assets/plugins/**/*.yaml",
  "assets/plugins/font-awesome/metadata/**",
  
]

# This catch-all formatter prevents warnings for files we don't want to format
# It's a no-op formatter that does nothing but claims to format everything else
[formatter.catchall]
command = "true"  # Unix command that always succeeds and does nothing
includes = [
  # Jekyll files
  "_includes/**",
  "_layouts/**",
  "_posts/**",
  "blog/**",
  "_config.yml",
  "_data/**",
  "index.html",     # Root index file with Jekyll template variables
  
  # Config files
  ".gitignore",
  ".envrc",
  "LICENSE*",
  "CNAME",
  "Gemfile*",
  "README.md",
  "CLAUDE.md",
  "flake.lock",
  "treefmt.toml",   # This configuration file itself
  
  # Binary files
  "**/*.jpg",
  "**/*.jpeg",
  "**/*.png",
  "**/*.gif",
  "**/*.svg",
  "**/*.ico",
  "**/*.eot",
  "**/*.ttf",
  "**/*.woff*",
  "**/*.otf",
  "**/*.pdf",
  "**/*.docx",
  "favicon.ico",
  
  # Third-party and generated code
  "assets/plugins/**",
  "css/**",
  "js/**",
  "**/font-awesome/**",
  
  # Minified files
  "**/*.min.*",
  "**/*.map",
  "**/min/**",
]